using Newtonsoft.Json;

namespace Illallangi.TripIt.Trips
{
    public class TripPurposeCollection
    {
        [JsonProperty(@"purpose_type_code")]
        public Purpose PurposeTypeCode { get; set; }

        [JsonProperty(@"is_auto_generated")]
        public bool IsAutoGenerated { get; set; }
    }
}
