namespace Illallangi.TripIt.Model
{
    using Newtonsoft.Json;

    public class TripItObject
    {
        [JsonProperty(@"id")]
        public string Id { get; set; }

        [JsonProperty(@"trip_id")]
        public string TripId { get; set; }

        [JsonProperty(@"is_client_traveler")]
        public bool IsClientTraveler { get; set; }

        [JsonProperty(@"relative_url")]
        public string RelativeUrl { get; set; }

        [JsonProperty(@"display_name")]
        public string DisplayName { get; set; }

        [JsonProperty(@"Image")]
        public Image[] Image { get; set; }

        [JsonProperty(@"Creator")]
        public Creator Creator { get; set; }

        [JsonProperty(@"is_display_name_auto_generated")]
        public bool IsDisplayNameAutoGenerated { get; set; }

        [JsonProperty(@"last_modified")]
        public string LastModified { get; set; }
    }
}
